### ISSUE TITLE
Pre-Trained LSTM.ipynb

### ISSUE THREAD

**Issue by itsergiu** [adeshpande3/LSTM-Sentiment-Analysis#10]
missing files: wordsList.npy, wordVectors.npy

import numpy as np
wordsList = np.load('wordsList.npy').tolist()
wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
wordVectors = np.load('wordVectors.npy')

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-667203141a0d> in <module>()
      1 import numpy as np
----> 2 wordsList = np.load('wordsList.npy').tolist()
      3 wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
      4 wordVectors = np.load('wordVectors.npy')

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    368     own_fid = False
    369     if isinstance(file, basestring):
--> 370         fid = open(file, "rb")
    371         own_fid = True
    372     elif is_pathlib_path(file):

FileNotFoundError: [Errno 2] No such file or directory: 'wordsList.npy'

**Comment by adeshpande3** [comment]
Read the README for information on downloading the data
