### ISSUE TITLE
Pre-Trained LSTM.ipynb -  Key rnn/basic_lstm_cell/kernel not found in checkpoint

### ISSUE THREAD

**Issue by itsergiu** [adeshpande3/LSTM-Sentiment-Analysis#11]
saver.restore(sess, tf.train.latest_checkpoint('/tmp/models'))

INFO:tensorflow:Restoring parameters from /tmp/models\pretrained_lstm.ckpt-90000

NotFoundError (see above for traceback): Key rnn/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save_1/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_4/tensor_names, save_1/RestoreV2_4/shape_and_slices)]]

**Comment by adeshpande3** [comment]
What version of Tensorflow are you using?

**Comment by MuneebMohammed** [comment]
I'm getting the same error while using tensorflow-1.4.0 with python 3.5

**Comment by MuneebMohammed** [comment]
Ok, got it. It works for tensorflow-1.1

**Comment by adeshpande3** [comment]
Yeah sorry about it. Haven't had time to make the code compatible with versions above 1.1, but yeah 1.1 should work.

**Comment by itsergiu** [comment]
import tensorflow as tf
print (tf.VERSION)
1.3.0

**Comment by adeshpande3** [comment]
You'll need to downgrade to version 1.1. Need to look into why the code is breaking for versions later than that
