### ISSUE TITLE
Issue while loading pretrained glove data

### ISSUE THREAD

**Issue by um255003** [adeshpande3/LSTM-Sentiment-Analysis#13]
Hi Adesh,

I am getting the following warning.

Warning (from warnings module):
  File "C:\Users\UM255003\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 134
    if params is None or params in ((), []):
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

Following is the code

import numpy as np
import tensorflow as tf
from os import listdir
from os.path import isfile, join

InPath = 'glove.6B.50d.txt'

wordsList = []
wordVector = []
file = open(InPath,'r',encoding='utf-8')
for line in file.readlines():
    row = line.strip().split(' ')
    wordsList.append(row[0])
    wordVector.append(row[1:])

print('Loaded Glove')
file.close()

wordVectors = np.asarray(wordVector)

print('Loading Done')

print(len(wordsList))
print(wordVectors.shape)

maxSeqLength = 10 #Maximum length of sentence
numDimensions = 300 #Dimensions for each word vector
firstSentence = np.zeros((maxSeqLength), dtype='int32')
firstSentence[0] = wordsList.index("i")
firstSentence[1] = wordsList.index("thought")
firstSentence[2] = wordsList.index("is")
firstSentence[3] = wordsList.index("movie")
firstSentence[4] = wordsList.index("was")
firstSentence[5] = wordsList.index("incredible")
firstSentence[6] = wordsList.index("and")
firstSentence[7] = wordsList.index("inspiring")
print(firstSentence.shape)
print(firstSentence)

print(wordVectors)

with tf.Session() as sess:
    print(tf.nn.embedding_lookup(wordVectors,firstSentence))

Can you please specify why I am getting the error.

P.S: I am new to tensor flow :)

**Comment by adeshpande3** [comment]
Which line is 134 referring to?

**Comment by um255003** [comment]
As per the warning it is referring to 134 line of embedding_ops.py which is part of tensor flow package.

**Comment by adeshpande3** [comment]
Is this a warning or an error? Also what line in the code is causing the warning to pop up?

**Comment by um255003** [comment]
this is a warning and the below lines are causing the warning

`with tf.Session() as sess:`
`print(tf.nn.embedding_lookup(wordVectors,firstSentence))`

**Comment by adeshpande3** [comment]
Looks like this is more of a Numpy issue as per https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur 
Since it's just a warning, I don't think you need to worry about it too much. Is it affecting the resulting that gets printed out?

**Comment by um255003** [comment]
Yeah its just a warning. No its not affecting the result.

Thank you for the support.
