### ISSUE TITLE
IndexError: index 250 is out of bounds for axis 0 with size 250

### ISSUE THREAD

**Issue by ghost** [adeshpande3/LSTM-Sentiment-Analysis#21]
Hi, 

![2018-02-01 3 21 53](https://user-images.githubusercontent.com/16621093/35664141-19748d80-0764-11e8-8c67-52f55eec14e3.png)

When I run the below code I got the **IndexError: index 250 is out of bounds for axis 0 with size 250**

I can not convert to the ids matrix as described in the tutorial. 

My python version is Python 3.5.2

P.S. Thank you so much for the awesome tutorial. The tutorial is really explaining the concepts very well 👍

**Comment by ghost** [comment]
Hi,

I added the condition  ` if indexCounter <250:` like below to avoid the  **IndexError: index 250 is out of bounds for axis 0 with size 250** error.

firstFile = np.zeros((maxSeqLength), dtype='int32')
with open(fname) as f:
    indexCounter = 0
    line=f.readline()
    cleanedLine = cleanSentences(line)
    split = cleanedLine.split()
    for word in split:
        try:
           ` if indexCounter <250:`
                firstFile[indexCounter] = wordsList.index(word)
        except ValueError:
            firstFile[indexCounter] = 399999 #Vector for unknown words
        indexCounter = indexCounter + 1
firstFile

![2018-02-01 4 10 41](https://user-images.githubusercontent.com/16621093/35665649-7cadb36c-076a-11e8-98a2-c1ab4b6fd28a.png)

But this result was different from the output of the tutorial. 

Is it okay? :)

**Comment by adeshpande3** [comment]
Yeah should be okay, it just depends on the order in which the files got extracted. Thanks for bringing this issue up, I'll add the check in the next push
