### ISSUE TITLE
Invalid training process

### ISSUE THREAD

**Issue by liuwei1206** [adeshpande3/LSTM-Sentiment-Analysis#34]
when I run the code without using the idsMatrix provided, the correct rate will not increase with the number of iterations increase. I get the idsMatrix By myself, but it doesn't work. When I use the idsMatrix provided, it work well, the correct rate will increase with the number of iterations increase. I don't know why, I try to compare the idsMatrix provided with the idsMatrix created by myself,  but I can't find what wrong!

**Comment by adeshpande3** [comment]
Are you trying to create the same sentiment analysis model on the same data? Remember, you can think of idsMatrix as being an N x M matrix where N is the number of training examples and M is the max sequence length. 

So, when you say that you're creating idsMatrix by yourself, are you doing that with the movie review dataset or with your own dataset. If you're doing it with your own, you should have >1000 examples at least.

**Comment by liuwei1206** [comment]
think you for your reply! In fact, I use the Provided positive and negative reviews to create the idsMatrix. And the method is same to your .npy code, Even the size of IdsMatrix I create is same to the IdsMatrix provided. But When I use the IdsMatrix I Create to run the model, the accuracy rate can not increase, and the loss can not decrease. I don't know why!

**Comment by adeshpande3** [comment]
What are the differences between the code you wrote to create the idsMatrix and my commented out code? If they are the same, can you look through the contents of the two idsMatrix arrays and see which values are different?

**Comment by liuwei1206** [comment]
I do it,  the only different may be the review's order in the idsMatrix, but the same review has the same content. For example, I find the 0_9.txt in positive reiviews has the same content in idsMatrix provided and idsMatrix Provided. But I find that the embedding file is kind of different, the first word in the origin glove file is 'the', but the first word in the provided wordsList is ''.But I think it’s influential, Because it is is a one-to-one correspondence between the wordslist and embedding.

**Comment by adeshpande3** [comment]
Um not sure why the correspondence is different. If you run the following, it should load in the words and corresponding vectors just fine. 
![image](https://user-images.githubusercontent.com/13543909/39165243-5702e7aa-4738-11e8-9703-68695d79dea8.png)

**Comment by liuwei1206** [comment]
In fact, I download the glove file myself. And I get the wordsList and the wordVectors by traversing the glove file. Yeah, I will find why, maybe I overlooked some details. And thank you for your help.
