### ISSUE TITLE
Running in batch doesn't work?

### ISSUE THREAD

**Issue by hedgy123** [adeshpande3/LSTM-Sentiment-Analysis#35]
Hi,
  I'd like to be able to run this code in batch, not as a Jupyter notebook.  So I wrote some python code (call it "batch.py") that I wanted to run as "python batch.py":

     numDimensions = 300
     maxSeqLength = 250
     batchSize = 24
     lstmUnits = 64
     numClasses = 2
     iterations = 100000

     import numpy as np
     wordsList = np.load('wordsList.npy').tolist()
     wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
     wordVectors = np.load('wordVectors.npy')

     import tensorflow as tf
     tf.reset_default_graph()

     labels = tf.placeholder(tf.float32, [batchSize, numClasses])
     input_data = tf.placeholder(tf.int32, [batchSize, maxSeqLength])

     data = tf.Variable(tf.zeros([batchSize, maxSeqLength, numDimensions]),dtype=tf.float32)
     data = tf.nn.embedding_lookup(wordVectors,input_data)

     lstmCell = tf.contrib.rnn.BasicLSTMCell(lstmUnits)
     lstmCell = tf.contrib.rnn.DropoutWrapper(cell=lstmCell, output_keep_prob=0.25)
     value, _ = tf.nn.dynamic_rnn(lstmCell, data, dtype=tf.float32)

     weight = tf.Variable(tf.truncated_normal([lstmUnits, numClasses]))
     bias = tf.Variable(tf.constant(0.1, shape=[numClasses]))
     value = tf.transpose(value, [1, 0, 2])
     last = tf.gather(value, int(value.get_shape()[0]) - 1)
     prediction = (tf.matmul(last, weight) + bias)

     correctPred = tf.equal(tf.argmax(prediction,1), tf.argmax(labels,1))
     accuracy = tf.reduce_mean(tf.cast(correctPred, tf.float32))

     sess = tf.InteractiveSession()
     saver = tf.train.Saver()
     saver.restore(sess, tf.train.latest_checkpoint('models'))

 But when I do "python batch.py" it crashes with an error that seems to indicate it could not restore the morel properly, even though it did it just fine in Jupyter notebook:

      Use the retry module or similar alternatives.
      2018-05-04 19:44:18.196624: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
      2018-05-04 19:44:18.544015: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key rnn/basic_lstm_cell/bias not found in checkpoint
         Traceback (most recent call last):
           File "/anaconda2/envs/py36base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
           File "/anaconda2/envs/py36base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
          File "/anaconda2/envs/py36base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
          File "/anaconda2/envs/py36base/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))  tensorflow.python.framework.errors_impl.NotFoundError: Key rnn/basic_lstm_cell/bias not found in checkpoint
	  [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

 
  I am not sure what I  can do to run this in batch?    Could you please help?    
  Thank you!

**Comment by adeshpande3** [comment]
Hmm not sure on first look, but it could have something to do with renaming of variables? https://github.com/KranthiGV/Pretrained-Show-and-Tell-model/issues/7

**Comment by hedgy123** [comment]
Yep, that was the issue and the solution you pointed out worked.  Thanks man!
