### ISSUE TITLE
Do I have to use wordslist if I can get wordvectors directly from words?

### ISSUE THREAD

**Issue by despagito** [adeshpande3/LSTM-Sentiment-Analysis#37]
I wonder if the reason you're using wordslist is because you can only get wordvectors from id, or you can't get a tensor if you transfer wordvector in advance.

**Comment by adeshpande3** [comment]
Yeah I mean you could also have a python dictionary that maps the words to their respective vectors. But yeah, the answer to your original question is you wouldn't need wordslist, it's just there to help you get the word vector.

**Comment by despagito** [comment]
I use Gensim and a pre-trained word vector model, and it seems impossible to transfer word vector sentence to a tensor because of the word vector in list. Any suggestion?

![image](https://user-images.githubusercontent.com/9820592/40594988-c3a5796c-6264-11e8-9daf-f1834db5d929.png)

![image](https://user-images.githubusercontent.com/9820592/40594975-b9584e12-6264-11e8-806f-5521329560a6.png)

**Comment by despagito** [comment]
Should I go back to `wordslist + embedding_lookup` way since this tensor conversion way won't work?

**Comment by despagito** [comment]
Thank you so much!
