### ISSUE TITLE
Why append [1,0] when i is even?

### ISSUE THREAD

**Issue by despagito** [adeshpande3/LSTM-Sentiment-Analysis#39]
Hi Adit, You seem to put all positive comments together, then why do you append [1,0] for all even lines?

```py
def getTrainBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        if (i % 2 == 0): 
            num = randint(1,11499)
            # why append [1,0] when i is even? 👇
            labels.append([1,0])
        else:
            num = randint(13499,24999)
            labels.append([0,1])
        arr[i] = ids[num-1:num]
    return arr, labels
```

**Comment by adeshpande3** [comment]
i represents the numbers from 1 to batchSize. So for example, if we have a batch size of 12, then we want 6 positive examples and 6 negative ones. During half of the iterations in that for loop, num will take on a value between 1 and 11499 (representing an example with a positive comment) while during the other half, it will be between 13499 and 24999 (representing an example with a negative comment). For the positive comments, we want [1,0] and for the negative ones, we want [0,1]

**Comment by despagito** [comment]
Uh, I see, I didn't figure out those numbers well, thank you so much!
