### ISSUE TITLE
Error when running the code 

### ISSUE THREAD

**Issue by alemap** [adeshpande3/LSTM-Sentiment-Analysis#8]
Hi! I'm not very expert in Python; when code is running, there is a error:

> Traceback (most recent call last):
  File "C:/Python36/SentimentAnalysisWithLSTM.py", line 187, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('models'))
  File "C:\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1557, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

I don't understand what is the problem.

**Comment by mamimaka** [comment]
I have the same issue
