### ISSUE TITLE
Large(>2GB) embedding lookup table cause value error.

### ISSUE THREAD

**Issue by shinys825** [adeshpande3/LSTM-Sentiment-Analysis#9]
From the code, large embedding loockup table causes an error.

The code below,
```
data = tf.nn.embedding_lookup(vector_array, input_data)
```
got this value error.
```
ValueError: Cannot create a tensor proto whose content is larger than 2GB
```
variable vector_array on the code is numpy array, and it contains about 14 million unique tokens and 100 dimension word vectors for each word.

Do you have anything to avoid that?
thank you.

**Comment by adeshpande3** [comment]
I'd maybe recommend seeing the first answer here https://stackoverflow.com/questions/46712934/how-to-deal-with-large2gb-embedding-lookup-table-in-tensorflow

**Comment by adeshpande3** [comment]
Closing since this is more of a tensorflow/dataset specific problem.
